server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
             - Path=/users/**
           filters:
             - name: CircuitBreaker
               args:
                 name: USER-SERVICE
                 fallbackuri: forward:/fallBackMethodForUser
         - id: DEPARTMENT-SERVICE
           uri: lb://DEPARTMENT-SERVICE
           predicates:
             - Path=/departments/**
           filters:
             - name: CircuitBreaker
               args:
                 name: DEPARTMENT-SERVICE
                 fallbackuri: forward:/fallBackMethodForDepartment
  main:
    web-application-type: reactive
    
debug: false


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
 